# Generated by Django 5.0.2 on 2024-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_products_created_at_products_discount_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
